In [ ]:
import numpy as np
import matplotlib.pyplot as plt


## **Question 1**

## **i)**

Yes this is a valid transformation. A valid transformation is Unitary as shown. Secondly, the transformation matrix is a square matrix with valid entries.

In [ ]:
transformation = np.array([[1/np.sqrt(2), 1/np.sqrt(2), 0],
                           [-1/np.sqrt(2), 1/np.sqrt(2), 0],
                           [0, 0, 1]])

transformation_transpose = transformation.transpose()

print(f'Transpose of transformation matrix :\n{transformation_transpose}')

product = np.matmul(transformation, transformation_transpose)

print('For tranformation to be valid, it must be unitary, \n the result of the product of the matrix and its adjoint is the identity')
print('Note floating point errors that sould equal zero')
print(product)

Transpose of transformation matrix :
[[ 0.70710678 -0.70710678  0.        ]
 [ 0.70710678  0.70710678  0.        ]
 [ 0.          0.          1.        ]]
For tranformation to be valid, it must be unitary, 
 the result of the product of the matrix and its adjoint is the identity
Note floating point errors that sould equal zero
[[1.00000000e+00 2.23711432e-17 0.00000000e+00]
 [2.23711432e-17 1.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]]


The colums of the matrix repersent the new basis vectors in terms of the old basis vectors. A wavefunction ψ's new wave function can be found by multiplying the old wavefunction with the transformation matrix Ψ'(x)=TΨ(x)

### **ii)**

In [ ]:
#transformation of operator A' = UAU^+
sigma = np.array([[6.6, 0, 0],
                  [0, 13.3, 0],
                  [0, 0, 19.8]])

sigma_transformed = np.matmul(np.matmul(transformation,sigma), transformation_transpose)

print(f'The operator (1) is transformed in the new basis as follows:\n{sigma_transformed}')

The operator (1) is transformed in the new basis as follows:
[[ 9.95  3.35  0.  ]
 [ 3.35  9.95  0.  ]
 [ 0.    0.   19.8 ]]


## **iii)**

In [ ]:
a,b=np.linalg.eig(sigma)
c,d=np.linalg.eig(sigma_transformed)

print('Eigenvalues of operator in original basis:', a)

print('Eigenvalues of operator in new basis:', c)


Eigenvalues of operator in original basis: [ 6.6 13.3 19.8]
Eigenvalues of operator in new basis: [13.3  6.6 19.8]


### **iv)**

In [ ]:
#transfomr state by mutiply by transformation matrix
psi = np.array([[1/np.sqrt(3)],
                [1/np.sqrt(3)],
                [1/np.sqrt(3)]])

psiprime = np.matmul(transformation, psi)
print('Note floating point error in middle of matrix = 0')
print(psiprime)


Note floating point error in middle of matrix = 0
[[ 8.16496581e-01]
 [-1.77961928e-17]
 [ 5.77350269e-01]]


## Question 2 i)
The first two eigenfunctions from the infinite double well are
- ψ1(x) = Const · sin(k1x)

- ψ2(x) = Const · sin(k2x)

Can be found either in |0⟩ or |1⟩ state
The Hamiltonian will be repersented by 2x2 matrix
H = [[⟨Ψ1|H|Ψ1>, ⟨Ψ1|H|Ψ2>] \\
    [⟨Ψ2|H|Ψ1>, ⟨Ψ2|H|Ψ2>]]

Assuming that the electron can only be found in the two lowest energy states, in the basis spanned by the eigenfunctions ψ1,2, the Hamiltonian operator of the system is a diagonal matrix
\\
Hψ = [[E1, 0], \\
      [0 , E2]]

      


In [ ]:
hamiltonian = np.array([[1.6 , 0],
                [0, 6]])

ii)

If we express the eigenfunctions as in terms of new basis
- ϕ1 = 1/sqrt(2) (|0⟩ + |1⟩)
- ϕ2 = 1/sqrt(2) (|0⟩ - |1⟩)

where these are defined as our new basis as column vectors

- ϕ1' = [[1/sqrt(2)], \\
 [1/sqrt(2)]]
- ϕ2' = [[1/sqrt(2)], \\
 [-1/sqrt(2)]]

 The matrix repersentation of the Hmiltonian operator in this new basis can be obtained by computing the matrix elements ⟨i|H|j⟩ using the basis transformations


In [ ]:
# Can be transformed by mutiplying by trasnfomation matrix to form quibit intonew basis
transformation2 = np.array([[1/np.sqrt(2), 1/np.sqrt(2)],
                           [1/np.sqrt(2), -1/np.sqrt(2)]])

hamiltonian_new_basis = np.matmul(transformation2, np.matmul(hamiltonian, transformation2))
print(hamiltonian_new_basis)


[[ 3.8 -2.2]
 [-2.2  3.8]]
