In [1]:
#The numpy library
import numpy as np


### Problem 1

Given the two vectors in a Hilbert space:
$$
|a\rangle = \left[ \begin{matrix} 0\\1/\sqrt{2}\\0\\-1/\sqrt{2} \end{matrix} \right] \qquad |b\rangle = \left[ \begin{matrix} \sqrt{3/5} \\\sqrt{1/5}\\0\\i\sqrt{1/5} \end{matrix} \right]
$$

* Check if the given states are normalized.



In [2]:
# Let us create the two vectors by simply listing their components:

a = np.array([[0, 1/np.sqrt(2), 0, -1/np.sqrt(2)]]).T

b = np.array([[np.sqrt(3/5), np.sqrt(1/5), 0, 1j*np.sqrt(1/5)]]).T

with np.printoptions(precision=3, suppress=True):
  print("The the vector a =  \n ", np.round(a,2), "\n")
  print("The norm of the vector a = %.2f"%np.linalg.norm(a), "\n")
  print("The the vector b =  \n ", np.round(b,2), "\n")
  print("The norm of the vector b = %.2f"%np.linalg.norm(b), "\n")

# Note the following commands:
# np.array(<list of components>) creates an array (line)
# np.array(<list of components >).T creates a transposed array (vector)
# round (a, 2)
# np.round (a, 2) leaves only two significant digits
# np.linalg.norm(array) calcualted the Euclidean norm of the vector

The the vector a =  
  [[ 0.  ]
 [ 0.71]
 [ 0.  ]
 [-0.71]] 

The norm of the vector a = 1.00 

The the vector b =  
  [[0.77+0.j  ]
 [0.45+0.j  ]
 [0.  +0.j  ]
 [0.  +0.45j]] 

The norm of the vector b = 1.00 




* Decompose the vectors into the $|00\rangle$, $|01\rangle$, $|10\rangle$ and $|11\rangle$ basis.


In [3]:
state0a = np.array([[1,0]]).T
state1a = np.array([[0,1]]).T
state0b = np.array([[1,0]]).T
state1b = np.array([[0,1]]).T

state0a0b = np.kron(state0a, state0b)
state0a1b = np.kron(state0a, state1b)
state1a0b = np.kron(state1a, state0b)
state1a1b = np.kron(state1a, state1b)

with np.printoptions(precision=3, suppress=True):
  print("Basis in the four dimensional space")
  print("State a = 0 and b = 0  is a basis vector  $\\lange 00 \\rangle$ \n", state0a0b)
  print("State a = 0 and b = 1  is a basis vector  $\\lange 01 \\rangle$ \n", state0a1b)
  print("State a = 1 and b = 0  is a basis vector  $\\lange 10 \\rangle$ \n", state1a0b)
  print("State a = 1 and b = 1  is a basis vector  $\\lange 11 \\rangle$ \n", state1a1b)

  # Projection and decomposition:

  print("Projection and decomposition of the vector a on to the basis")
  print ("Projection of the vector a onto the state 00: ", (np.transpose(a) @ state0a0b) [0][0] )
  print ("Projection of the vector a onto the state 01: ", np.transpose(a) @ state0a1b )
  print ("Projection of the vector a onto the state 10: ", np.transpose(a) @ state1a0b )
  print ("Projection of the vector a onto the state 11: ", np.transpose(a) @ state1a1b )

  print("\nProjection and decomposition of the vector b on to the basis")
  print ("Projection of the vector b onto the state 00: ", np.transpose(b) @ state0a0b )
  print ("Projection of the vector b onto the state 01: ", np.transpose(b) @ state0a1b )
  print ("Projection of the vector b onto the state 10: ", np.transpose(b) @ state1a0b )
  print ("Projection of the vector b onto the state 11: ", np.transpose(b) @ state1a1b )


#x = np.transpose(a) @ state0a0b
#print(x[0][0])


Basis in the four dimensional space
State a = 0 and b = 0  is a basis vector  $\lange 00 \rangle$ 
 [[1]
 [0]
 [0]
 [0]]
State a = 0 and b = 1  is a basis vector  $\lange 01 \rangle$ 
 [[0]
 [1]
 [0]
 [0]]
State a = 1 and b = 0  is a basis vector  $\lange 10 \rangle$ 
 [[0]
 [0]
 [1]
 [0]]
State a = 1 and b = 1  is a basis vector  $\lange 11 \rangle$ 
 [[0]
 [0]
 [0]
 [1]]
Projection and decomposition of the vector a on to the basis
Projection of the vector a onto the state 00:  0.0
Projection of the vector a onto the state 01:  [[0.707]]
Projection of the vector a onto the state 10:  [[0.]]
Projection of the vector a onto the state 11:  [[-0.707]]

Projection and decomposition of the vector b on to the basis
Projection of the vector b onto the state 00:  [[0.775+0.j]]
Projection of the vector b onto the state 01:  [[0.447+0.j]]
Projection of the vector b onto the state 10:  [[0.+0.j]]
Projection of the vector b onto the state 11:  [[0.+0.447j]]


* One measures the system in a state $|a\rangle$. What is the probability that the first bit in the measurement eqauls $1$?

* One measures the system in a state $|b\rangle$. Whar is the probability that the first bit in the measurement equals $0$?

In [4]:
# Two components of the state vector 10 and 11 contain the outcome that the first qubit is 1:
# |10> when a = 1 and b = 0 and |10> when a = 1 and b = 1
# Hence the probability is the projection of the vector a onto the state 10 squared
# plus the projection of the vector a onto the state 11 squared, square root

with np.printoptions(precision=3, suppress=True):
  Prob_a1 = np.sqrt((np.transpose(a) @ state1a0b)[0][0]**2 + (np.transpose(a) @ state1a1b)[0][0]**2 )

  print("Probability that the first qubit is measured as 1: ", Prob_a1)

  Prob_b0 = np.sqrt((np.transpose(b) @ state0a0b)[0][0]**2 + (np.transpose(b) @ state0a1b)[0][0]**2 )

  print("Probability that the first qubit is measured as 1: ", Prob_b0)

Probability that the first qubit is measured as 1:  0.7071067811865475
Probability that the first qubit is measured as 1:  (0.8944271909999159+0j)


* We want to build a new quantum state as a superposition. Is the state  $|c\rangle = 3|a\rangle-2|b\rangle$ allowed?  

* What should one do to make this state a proper superposition state?

In [5]:
with np.printoptions(precision=3, suppress=True):
  # Let us build the superposition vector c:
  c = 3*a - 2*b
  print("|c> = \n",c)

  # Check the norm ofthe vector c:
  print("The norm of c = %.2f"%np.linalg.norm(c))

  # To get a valid quantum state, we normalise the vector c:
  c = c/np.linalg.norm(c)
  print("The normalized |c> = \n",c)


|c> = 
 [[-1.549+0.j   ]
 [ 1.227+0.j   ]
 [ 0.   +0.j   ]
 [-2.121-0.894j]]
The norm of c = 3.03
The normalized |c> = 
 [[-0.511+0.j   ]
 [ 0.404+0.j   ]
 [ 0.   +0.j   ]
 [-0.699-0.295j]]


* Calculate the projection of the vector b onto the vector l $\langle b|a \rangle$.

In [6]:
ba = np.dot(np.conjugate(b.T),a)
print("<b|a> = %.2f + i%.2f"%(np.real(ba), np.imag(ba)))

<b|a> = 0.32 + i0.32


/tmp/ipykernel_81224/2901170411.py:2: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  print("<b|a> = %.2f + i%.2f"%(np.real(ba), np.imag(ba)))


* Calculate the transformation $|a\rangle \otimes \langle b|$:

In [7]:
ab = np.kron(a,np.conjugate(b.T))
with np.printoptions(precision=3, suppress=True):
  print("|a> <b| = \n",ab)

|a> <b| = 
 [[ 0.   +0.j     0.   +0.j     0.   +0.j     0.   +0.j   ]
 [ 0.548+0.j     0.316+0.j     0.   +0.j     0.   -0.316j]
 [ 0.   +0.j     0.   +0.j     0.   +0.j     0.   +0.j   ]
 [-0.548+0.j    -0.316+0.j     0.   +0.j     0.   +0.316j]]


* Assuming the Hamiltonian:
$$
H = \left[\begin{matrix}
1 & 0 & 0 & 0 \\
0 & 1 & 0 & 0 \\
0 & 0 & 0 & i \\
0 & 0 & -i& 0
\end{matrix}\right]
$$
Calculate the average value: $\langle a|H|a\rangle$

In [8]:
H = np.array([[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 0, 1j], [0, 0, -1j, 0]])
aHa = np.matmul(np.conjugate(a.T),np.matmul(H, a))

In [9]:
print("<a|H|a> = %.2f + i%.2f"%(np.real(aHa), np.imag(aHa)))

<a|H|a> = 0.50 + i0.00


/tmp/ipykernel_81224/562401028.py:1: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  print("<a|H|a> = %.2f + i%.2f"%(np.real(aHa), np.imag(aHa)))


### Problem 2

Given operator $H$:
$$
H = \left[\begin{matrix}
1 & 0 & 0 & 0 \\
0 & 1 & 0 & 0 \\
0 & 0 & 0 & i \\
0 & 0 & -i& 0
\end{matrix}\right]
$$

* Check if $H$ is Hermitian ($H^{\dagger} = H$)

In [10]:
print("H = \n",H)

H = 
 [[ 1.+0.j  0.+0.j  0.+0.j  0.+0.j]
 [ 0.+0.j  1.+0.j  0.+0.j  0.+0.j]
 [ 0.+0.j  0.+0.j  0.+0.j  0.+1.j]
 [ 0.+0.j  0.+0.j -0.-1.j  0.+0.j]]


In [11]:
print("H+ = \n",np.conjugate(H.T))

H+ = 
 [[ 1.-0.j  0.-0.j  0.-0.j  0.-0.j]
 [ 0.-0.j  1.-0.j  0.-0.j  0.-0.j]
 [ 0.-0.j  0.-0.j  0.-0.j -0.+1.j]
 [ 0.-0.j  0.-0.j  0.-1.j  0.-0.j]]


* Calculate the eigenvalues of $H$:

In [12]:
eval, evec = np.linalg.eig(H)

In [13]:
print(eval)

[ 1.+0.j -1.+0.j  1.+0.j  1.+0.j]


### Problem 3

Check the eigenvalues of H remain unchanged after unitary transformation in Tutorial problem 4



In [14]:
H_psi = np.array([[1.6, 0], [0, 6]])
H_phi = np.array([[3.8, -2.2], [-2.2, 3.8]])

eval_psi, evec_psi = np.linalg.eig(H_psi)
eval_phi, evec_phi = np.linalg.eig(H_phi)

print(eval_psi)
print(eval_phi)

[1.6 6. ]
[6.  1.6]
